# Generated by Django 5.2.16 on 2026-07-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondfactorrecoveryrequest',
            options={'permissions': [('decide_recovery_request', 'Can approve or deny a second-factor recovery request')]},
        ),
    ]
