# Generated by Django 5.2.16 on 2026-07-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_secondfactorrecoveryrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondfactor',
            name='last_verified_step',
            field=models.BigIntegerField(blank=True, help_text='The TOTP time-step last accepted, so the same code cannot be replayed.', null=True),
        ),
    ]
