# Generated by Django 5.2.16 on 2026-07-19 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bonus_cycle',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'salary_structure',
            },
        ),
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed'), ('percentage_of_salary', 'Percentage of salary')], max_length=32)),
                ('amount_or_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('is_taxable', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'allowance_type',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_or_rate__gte', 0)), name='allowance_type_amount_gte_0'), models.CheckConstraint(condition=models.Q(models.Q(('calculation_method', 'percentage_of_salary'), _negated=True), ('amount_or_rate__lte', 1), _connector='OR'), name='allowance_type_percentage_rate_lte_1')],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'benefit',
                'constraints': [models.CheckConstraint(condition=models.Q(('cost__isnull', True), ('cost__gte', 0), _connector='OR'), name='benefit_cost_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='BenefitEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='compensation.benefit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='benefit_enrollments', to='employees.employee')),
            ],
            options={
                'db_table': 'benefit_enrollment',
            },
        ),
        migrations.CreateModel(
            name='PayGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pay_grades', to='compensation.salarystructure')),
            ],
            options={
                'db_table': 'pay_grade',
            },
        ),
        migrations.CreateModel(
            name='BonusAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bonus_awards', to='employees.employee')),
                ('bonus_cycle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='awards', to='compensation.bonuscycle')),
            ],
            options={
                'db_table': 'bonus_award',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='bonus_award_amount_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employee_allowances', to='compensation.allowancetype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='allowances', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_allowance',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_override__isnull', True), ('amount_override__gte', 0), _connector='OR'), name='employee_allowance_amount_override_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='CompensationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_superseded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compensation_records', to='employees.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pay_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='compensation_records', to='compensation.paygrade')),
            ],
            options={
                'db_table': 'compensation_record',
                'constraints': [models.CheckConstraint(condition=models.Q(('base_salary__gte', 0)), name='compensation_record_base_salary_gte_0')],
            },
        ),
        migrations.AddConstraint(
            model_name='paygrade',
            constraint=models.CheckConstraint(condition=models.Q(('min_salary__gte', 0)), name='pay_grade_min_salary_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='paygrade',
            constraint=models.CheckConstraint(condition=models.Q(('max_salary__gte', models.F('min_salary'))), name='pay_grade_max_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='paygrade',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'name'), name='pay_grade_unique_name_per_structure'),
        ),
    ]
