# Generated by Django 5.2.16 on 2026-07-19 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_alter_allowancetype_amount_or_rate_and_more'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compensationrecord',
            constraint=models.CheckConstraint(condition=models.Q(('is_superseded', False), ('effective_to__isnull', False), _connector='OR'), name='compensation_record_superseded_has_effective_to'),
        ),
        migrations.AddConstraint(
            model_name='compensationrecord',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='compensation_record_effective_to_gte_effective_from'),
        ),
    ]
