# Generated by Django 5.2.16 on 2026-07-19 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('headcount', 'Headcount'), ('leave_utilization', 'Leave utilization'), ('turnover', 'Turnover'), ('payroll_cost', 'Payroll cost'), ('payroll_summary', 'Payroll summary')], max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('object_key', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_export',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('generated_at__isnull', False), ('object_key__isnull', False), ('status', 'complete')), models.Q(models.Q(('status', 'complete'), _negated=True), ('object_key__isnull', True), ('generated_at__isnull', True)), _connector='OR'), name='report_export_complete_fields'), models.CheckConstraint(condition=models.Q(models.Q(('failed_reason__isnull', False), ('status', 'failed')), models.Q(models.Q(('status', 'failed'), _negated=True), ('failed_reason__isnull', True)), _connector='OR'), name='report_export_failed_reason')],
            },
        ),
    ]
