# Generated by Django 5.2.16 on 2026-07-18 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pending_task', 'Pending task'), ('request_update', 'Request update')], max_length=32)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('both', 'Both')], max_length=16)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('related_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_id', models.BigIntegerField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(db_column='recipient_user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
