# Generated by Django 5.2.16 on 2026-07-18 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGrantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refused', 'Refused')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='role_grant_requests_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='auth.group')),
                ('subject', models.ForeignKey(help_text='The user the role would be granted to.', on_delete=django.db.models.deletion.RESTRICT, related_name='role_grant_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_grant_request',
                'permissions': [('approve_role_grant', 'Can approve or refuse a privileged role-grant request')],
                'constraints': [models.CheckConstraint(condition=models.Q(('requester', models.F('subject')), _negated=True), name='role_grant_request_no_self_grant'), models.CheckConstraint(condition=models.Q(('approver__isnull', True), models.Q(('approver', models.F('requester')), _negated=True), _connector='OR'), name='role_grant_request_approver_not_requester')],
            },
        ),
    ]
