# Generated by Django 5.2.16 on 2026-07-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='reporting_relationship', to='employees.employee')),
                ('manager_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='direct_reports', to='employees.employee')),
            ],
            options={
                'db_table': 'reporting_relationship',
                'constraints': [models.CheckConstraint(condition=models.Q(('employee', models.F('manager_employee')), _negated=True), name='reporting_relationship_not_self_managed')],
            },
        ),
    ]
