# Generated by Django 5.2.16 on 2026-07-19 06:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='initiated_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_run',
                'permissions': [('approve_payroll_run', 'Can approve a payroll run for finalisation')],
            },
        ),
        migrations.CreateModel(
            name='BankTransferFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_run', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='bank_transfer_file', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'bank_transfer_file',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payslip',
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('basic_salary', 'Basic salary'), ('allowance', 'Allowance'), ('deduction_statutory_paye', 'PAYE'), ('deduction_statutory_ssnit_tier1', 'SSNIT Tier 1'), ('deduction_statutory_ssnit_tier2', 'SSNIT Tier 2'), ('deduction_statutory_ssnit_tier3', 'SSNIT Tier 3'), ('deduction_other', 'Other deduction')], max_length=40)),
                ('source_type', models.CharField(blank=True, max_length=64, null=True)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='payroll.payslip')),
            ],
            options={
                'db_table': 'payslip_line',
            },
        ),
        migrations.CreateModel(
            name='StatutoryRateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('paye', 'PAYE'), ('ssnit_tier1', 'SSNIT Tier 1'), ('ssnit_tier2', 'SSNIT Tier 2'), ('ssnit_tier3', 'SSNIT Tier 3')], max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rates', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'statutory_rate_table',
                'constraints': [models.UniqueConstraint(fields=('rate_type', 'effective_from'), name='statutory_rate_unique_type_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('initiated_by')), _negated=True), _connector='OR'), name='payroll_run_approver_not_initiator'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('period_start', 'period_end'), name='payroll_run_unique_period'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='payslip_unique_run_employee'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payslip_line_amount_gte_0'),
        ),
    ]
