# Generated by Django 5.2.16 on 2026-07-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_seed_placeholder_statutory_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='object_key',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
