# Generated by Django 5.2.16 on 2026-07-19 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0003_payslip_object_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_run_period_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('gross_pay__gte', 0)), name='payslip_gross_pay_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('net_pay__gte', 0)), name='payslip_net_pay_gte_0'),
        ),
    ]
