# Generated by Django 5.2.16 on 2026-07-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidateapplication',
            constraint=models.UniqueConstraint(fields=('candidate', 'posting'), name='unique_candidate_posting_application'),
        ),
    ]
