# Generated by Django 5.2.16 on 2026-07-19 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
        ('recruitment', '0002_candidateapplication_unique_candidate_posting_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='offered_pay_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='offer_letters', to='compensation.paygrade'),
        ),
    ]
