# Generated by Django 5.2.16 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_offerletter_offered_pay_grade'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobrequisition',
            constraint=models.CheckConstraint(
                condition=models.Q(approved_by__isnull=True) | ~models.Q(approved_by=models.F('requested_by')),
                name='job_requisition_approver_not_requester',
            ),
        ),
    ]
